In [2]:
# Import Numpy
import numpy as np  # <-- Add this line first!
b = np.array([3, 4, 5],dtype='int16')
print(b)

[3 4 5]


In [1]:
!pip install numpy

In [ ]:
# Define an array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
# Get Shape
a.shape

(2, 3)

In [12]:
# Get Dimension
b.ndim

1

In [13]:
# Get Type
a.dtype

dtype('int64')

In [17]:
# Get Size
b.itemsize

2

In [3]:
c = np.array([[1,2,3,4,5,6,7,8,9,10,11],[3,2,5,1,12,43,65,89,34,12,0]])
print(c)

NameError: name 'np' is not defined

In [30]:
c.shape

(2, 11)

In [35]:
c[1,5]

np.int64(43)

In [2]:
c[0,:]

NameError: name 'c' is not defined

In [4]:
import numpy as np
d = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(d)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [ ]:
d[0,:] 

array([1, 2, 3, 4, 5])

In [5]:
d[:,4] # a[r,c]  and ":" means full row or coloumn

array([5, 1])

In [14]:
d[1,1:4:2]  # starting index:end index:spacing

array([4, 2])

In [23]:
d[1,4]=20
d[:,3]=[0,0]        #  Changing values
d[0,:]=[2,5,6,7,8]
print(d)

[[ 2  5  6  7  8]
 [ 5  4  3  0 20]]


In [5]:
import numpy as np
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# Get specific element
b[:,0,0]

array([1, 5])

In [11]:
# All in Matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
#Any other number
np.full((3,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [15]:
np.full_like(b,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [16]:
np.random.random_sample(b.shape)

array([[[0.49084753, 0.32735192],
        [0.47260731, 0.5533311 ]],

       [[0.68433433, 0.25851876],
        [0.1363818 , 0.38467736]]])

In [19]:
np.random.randint(0,3, size=(3,3))

array([[1, 1, 0],
       [1, 0, 2],
       [0, 0, 0]], dtype=int32)

In [ ]:
import numpy as np #type:ignore
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
#repeat AN ARRAY
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
x=np.full((6,6),5)
y=np.full((2,2),3)
y[1,1]=7
print(y)
x[2:4,2:4]=y
print(x)

[[3 3]
 [3 7]]
[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 3 3 5 5]
 [5 5 3 7 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [9]:
import numpy as np  

# Columns: [Day of Month, Temperature (°C), Units Sold]  
sales_data = np.array([  
    [1, 28, 45],  
    [2, 30, 52],  
    [3, 32, 60],  
    [4, 29, 48],  
    [5, 31, 58],  
    [6, 28, 42],  
    [7, 33, 64],  
    [8, 34, 68],  
    [9, 26, 40],  
    [10, 31, 55]  
])  

In [ ]:
avg = np.mean(sales_data[:,1])
print(f"Average Temperature is {avg}")

Average Temperature is 30.2


In [19]:
sd = sales_data[sales_data[:,2]>50]
print(f"Days with sales > 50 ={sd[:,2]}")

Days with sales > 50 =[52 60 58 64 68 55]


In [24]:
core = np.corrcoef(sales_data[:,1],sales_data[:,2])[0,1]
print(f"Corelation = {core:.2f}")

Corelation = 0.99


In [27]:
x=sales_data[:,1]
y=sales_data[:,2]
m,b=np.polyfit(x,y,deg=1)
prediction = m*35+b
print(f"Predicted sales at 35 degree= {prediction:.2f}")


Predicted sales at 35 degree= 71.21


In [1]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

B = np.array([
    [2, 3, 5],
    [1, 5, 2],
    [4, 7, 6],
    [9, 13, 11]
])

In [ ]:
import numpy as np

# Student names
students = np.array(["Alice", "Bob", "Charlie", "David", "Eve"])

# Scores in Math, Physics, Chemistry (rows: students, columns: subjects)
scores = np.array([
    [85, 90, 78],   # Alice
    [70, 82, 75],   # Bob
    [92, 88, 94],   # Charlie
    [65, 73, 80],   # David
    [78, 85, 72]    # Eve
])

In [11]:
mean = np.mean(scores,axis=0)
print(mean)

[78.  83.6 79.8]


In [14]:
sum = np.sum(scores,axis=1)
max_index = np.argmax(sum)
max = students[max_index]
print(max)

Charlie


In [19]:
corelation = np.corrcoef(scores,rowvar=False)
print(corelation)

[[1.         0.88305411 0.59750347]
 [0.88305411 1.         0.20157394]
 [0.59750347 0.20157394 1.        ]]


In [16]:
max_score = np.max(scores)
min_score = np.min(scores)
normalize = (scores-min_score)/(max_score-min_score)
print(normalize)

[[0.68965517 0.86206897 0.44827586]
 [0.17241379 0.5862069  0.34482759]
 [0.93103448 0.79310345 1.        ]
 [0.         0.27586207 0.51724138]
 [0.44827586 0.68965517 0.24137931]]


In [18]:
min_vals = np.min(scores, axis=0)  # [65, 73, 72] (min of each subject)
max_vals = np.max(scores, axis=0)  # [92, 90, 94] (max of each subject)
normalized_scores = (scores - min_vals) / (max_vals - min_vals)
print(normalized_scores)

[[0.74074074 1.         0.27272727]
 [0.18518519 0.52941176 0.13636364]
 [1.         0.88235294 1.        ]
 [0.         0.         0.36363636]
 [0.48148148 0.70588235 0.        ]]


In [20]:
# Extract individual subject columns
math = scores[:, 0]
physics = scores[:, 1]
chemistry = scores[:, 2]

# Manually compute Math vs Physics correlation
cov_math_physics = np.cov(math, physics, ddof=1)[0, 1]  # Covariance
std_math, std_physics = np.std(math, ddof=1), np.std(physics, ddof=1)
r_manual = cov_math_physics / (std_math * std_physics)
print("Manual Math vs Physics correlation:", r_manual)  # Should match 0.658

Manual Math vs Physics correlation: 0.8830541100808039


In [22]:
w = input("H: ")
print(w)

Mazhar


Question 2

In [13]:
features = houses[:, :-1]
mean = np.mean(features,axis=0)
std = np.std(features,axis=0)
z = (features-mean)/std
print(z)

[[ 0.19882525  0.14285714 -0.15075567  0.49886255]
 [-1.34759334 -1.28571429 -1.6583124   1.84713971]
 [-0.68484252 -1.28571429 -0.15075567 -0.17527603]
 [ 2.18707771  1.57142857  1.35680105 -0.84941461]
 [-0.02209169  0.14285714  0.60302269 -1.52355319]
 [-0.46392558  0.14285714 -0.15075567 -0.57975918]
 [ 1.08249301  1.57142857  1.35680105 -1.11907004]
 [-0.24300863  0.14285714 -0.15075567  0.49886255]
 [ 0.41974219  0.14285714  0.60302269  0.22920712]
 [-1.1266764  -1.28571429 -1.6583124   1.17300113]]


In [12]:
# Extract features (exclude Price)
features = houses[:, :-1]  # All columns except last (Price)

# Compute mean and std for each feature
mean = np.mean(features, axis=0)
std = np.std(features, axis=0)

# Z-score normalization
normalized_features = (features - mean) / std
print("Normalized Features:\n", normalized_features)

Normalized Features:
 [[ 0.19882525  0.14285714 -0.15075567  0.49886255]
 [-1.34759334 -1.28571429 -1.6583124   1.84713971]
 [-0.68484252 -1.28571429 -0.15075567 -0.17527603]
 [ 2.18707771  1.57142857  1.35680105 -0.84941461]
 [-0.02209169  0.14285714  0.60302269 -1.52355319]
 [-0.46392558  0.14285714 -0.15075567 -0.57975918]
 [ 1.08249301  1.57142857  1.35680105 -1.11907004]
 [-0.24300863  0.14285714 -0.15075567  0.49886255]
 [ 0.41974219  0.14285714  0.60302269  0.22920712]
 [-1.1266764  -1.28571429 -1.6583124   1.17300113]]


In [22]:
p = houses[:,-1]
h_p_i = np.where(p==np.max(p))
print(houses[h_p_i])

[[  3000.      4.      3.     10. 700000.]]


In [18]:
np.set_printoptions(suppress=True)  # Disable scientific notation

In [24]:
bedroom = houses[:,1]
b = bedroom > 2
avg_bd = np.mean(b)
print(b)
print(avg_bd)

[ True False False  True  True  True  True  True  True False]
0.7


In [10]:
bedrooms = houses[:, 1]  # Bedrooms column
prices = houses[:,-1]
avg_price_3plus_bedrooms = np.mean(prices[bedrooms > 2])
print(prices[bedrooms > 2])
print("Avg price (>2 bedrooms):", avg_price_3plus_bedrooms)

[500000. 700000. 600000. 480000. 650000. 520000. 550000.]
Avg price (>2 bedrooms): 571428.5714285715


Question 3

In [10]:
import numpy as np # type: ignore

# Columns: [Area (sq ft), Bedrooms, Bathrooms, Age (years), Price ($)]
houses = np.array([
    [2100, 3, 2, 20, 500000],  # House 1
    [1400, 2, 1, 30, 350000],  # House 2
    [1700, 2, 2, 15, 425000],  # House 3
    [3000, 4, 3, 10, 700000],  # House 4
    [2000, 3, 2.5, 5, 600000], # House 5
    [1800, 3, 2, 12, 480000],  # House 6
    [2500, 4, 3, 8, 650000],   # House 7
    [1900, 3, 2, 20, 520000],  # House 8
    [2200, 3, 2.5, 18, 550000],# House 9
    [1500, 2, 1, 25, 400000]   # House 10
])

Calculate the average price of houses with >2 bedrooms.



In [8]:
bedrooms = houses[:,1]
prices = houses[:,-1]
b_g_2 = np.mean(prices[bedrooms>2])
print(f"{b_g_2:.1f}")

571428.6


Compute the correlation between:





i. Area and Price


In [21]:
Area = houses[:,0]
cor_A_P = np.corrcoef(Area,prices)[0,1]
print(f"{cor_A_P}")

0.9394469945282904


ii. Bedrooms and Price


In [25]:
cor_B_P = np.corrcoef(bedrooms,prices)[0,1]
print(f"{cor_B_P}")

0.9395705673577847


Strongest Corelation

In [26]:
if cor_A_P > cor_B_P:
    print(f"Strongest Corelation is Area")
else:
    print(f"Strongest Corelation is Bedroom")


Strongest Corelation is Bedroom


In [27]:
# Extract columns
area = houses[:, 0]
bedrooms = houses[:, 1]
price = houses[:, -1]

# Compute correlations
corr_area_price = np.corrcoef(area, price)[0, 1]
corr_bedrooms_price = np.corrcoef(bedrooms, price)[0, 1]

strongest_correlation = "Area" if abs(corr_area_price) > abs(corr_bedrooms_price) else "Bedrooms"
print("Correlation (Area vs Price):", corr_area_price)
print("Correlation (Bedrooms vs Price):", corr_bedrooms_price)
print("Strongest correlation:", strongest_correlation)

Correlation (Area vs Price): 0.9394469945282904
Correlation (Bedrooms vs Price): 0.9395705673577847
Strongest correlation: Bedrooms


Create a sub-dataset of houses ≤15 years old and compute their average price.



In [37]:
age =houses[:,-2]
h_l_15 = houses[age <= 15]
print(h_l_15)
avg_h_l_15 = np.mean(prices[age <= 15])
avgi_h_l_15 = np.mean(h_l_15[:,-1])
print(avg_h_l_15)
print(avgi_h_l_15)

[[  1700.       2.       2.      15.  425000. ]
 [  3000.       4.       3.      10.  700000. ]
 [  2000.       3.       2.5      5.  600000. ]
 [  1800.       3.       2.      12.  480000. ]
 [  2500.       4.       3.       8.  650000. ]]
571000.0
571000.0


In [34]:
print(prices[age <= 15])
print(age <= 15)

[425000. 700000. 600000. 480000. 650000.]
[False False  True  True  True  True  True False False False]


In [35]:
age = houses[:, 3]
young_houses = houses[age <= 15]
young_houses_avg_price = np.mean(young_houses[:, -1])
print("Avg price (≤15 years old):", young_houses_avg_price)

Avg price (≤15 years old): 571000.0
